name: deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: srt32/hugo-action@v0.0.3
      - name: Build the site using hugo and deploy the site using rsync
      - run: ./deploy.sh
